In [1]:
import pandas as pd;

In [ ]:
print(pd)
df=pd.read_csv('dataset.csv')
#fetch first 5 rows
print(df.head(5))
print(df.describe())

<module 'pandas' from 'c:\\Projects\\DataScience\\venv\\lib\\site-packages\\pandas\\__init__.py'>
                              name  \
0     2024 Jeep Wagoneer Series II
1  2024 Jeep Grand Cherokee Laredo
2         2024 GMC Yukon XL Denali
3       2023 Dodge Durango Pursuit
4            2024 RAM 3500 Laramie

                                         description   make           model  \
0  \n      \n        Heated Leather Seats, Nav Sy...   Jeep        Wagoneer
1  Al West is committed to offering every custome...   Jeep  Grand Cherokee
2                                                NaN    GMC        Yukon XL
3  White Knuckle Clearcoat 2023 Dodge Durango Pur...  Dodge         Durango
4  \n      \n        2024 Ram 3500 Laramie Billet...    RAM            3500

   year    price                                             engine  \
0  2024  74600.0                            24V GDI DOHC Twin Turbo
1  2024  50170.0                                                OHV
2  2024  96410.0  6.2L V-8 gasoline direct injection, variable v...
3  2023  46835.0                                       16V MPFI OHV
4  2024  81663.0                           24V DDI OHV Turbo Diesel

   cylinders      fuel  mileage       transmission       trim          body  \
0        6.0  Gasoline     10.0  8-Speed Automatic  Series II           SUV
1        6.0  Gasoline      1.0  8-Speed Automatic     Laredo           SUV
2        8.0  Gasoline      0.0          Automatic     Denali           SUV
3        8.0  Gasoline     32.0  8-Speed Automatic    Pursuit           SUV
4        6.0    Diesel     10.0  6-Speed Automatic    Laramie  Pickup Truck

   doors           exterior_color    interior_color        drivetrain
0    4.0                    White      Global Black  Four-wheel Drive
1    4.0                 Metallic      Global Black  Four-wheel Drive
2    4.0             Summit White  Teak/Light Shale  Four-wheel Drive
3    4.0  White Knuckle Clearcoat             Black   All-wheel Drive
4    4.0                   Silver             Black  Four-wheel Drive
              year          price   cylinders      mileage       doors
count  1002.000000     979.000000  897.000000   968.000000  995.000000
mean   2023.916168   50202.985700    4.975474    69.033058    3.943719
std       0.298109   18700.392062    1.392526   507.435745    0.274409
min    2023.000000       0.000000    0.000000     0.000000    2.000000
25%    2024.000000   36600.000000    4.000000     4.000000    4.000000
50%    2024.000000   47165.000000    4.000000     8.000000    4.000000
75%    2024.000000   58919.500000    6.000000    13.000000    4.000000
max    2025.000000  195895.000000    8.000000  9711.000000    5.000000
name               object
description        object
make               object
model              object
year                int64
price             float64
engine             object
cylinders         float64
fuel               object
mileage           float64
transmission       object
trim               object
body               object
doors             float64
exterior_color     object
interior_color     object
drivetrain         object
dtype: object

In [ ]:
print(df.dtypes)
print(df.isnull())
print(df.isnull().sum())
print(df.isnull().sum(axis=1))

name               object
description        object
make               object
model              object
year                int64
price             float64
engine             object
cylinders         float64
fuel               object
mileage           float64
transmission       object
trim               object
body               object
doors             float64
exterior_color     object
interior_color     object
drivetrain         object
dtype: object
0       0
1       0
2       1
3       0
4       0
       ..
997     0
998     0
999     0
1000    0
1001    0
Length: 1002, dtype: int64

In [ ]:
df_filed=df.fillna(0)

,name,description,make,model,year,price,engine,cylinders,fuel,mileage,transmission,trim,body,doors,exterior_color,interior_color,drivetrain
0,2024 Jeep Wagoneer Series II,"\n \n Heated Leather Seats, Nav Sy...",Jeep,Wagoneer,2024,74600.0,24V GDI DOHC Twin Turbo,6.0,Gasoline,10.0,8-Speed Automatic,Series II,SUV,4.0,White,Global Black,Four-wheel Drive
1,2024 Jeep Grand Cherokee Laredo,Al West is committed to offering every custome...,Jeep,Grand Cherokee,2024,50170.0,OHV,6.0,Gasoline,1.0,8-Speed Automatic,Laredo,SUV,4.0,Metallic,Global Black,Four-wheel Drive
2,2024 GMC Yukon XL Denali,0,GMC,Yukon XL,2024,96410.0,"6.2L V-8 gasoline direct injection, variable v...",8.0,Gasoline,0.0,Automatic,Denali,SUV,4.0,Summit White,Teak/Light Shale,Four-wheel Drive
3,2023 Dodge Durango Pursuit,White Knuckle Clearcoat 2023 Dodge Durango Pur...,Dodge,Durango,2023,46835.0,16V MPFI OHV,8.0,Gasoline,32.0,8-Speed Automatic,Pursuit,SUV,4.0,White Knuckle Clearcoat,Black,All-wheel Drive
4,2024 RAM 3500 Laramie,\n \n 2024 Ram 3500 Laramie Billet...,RAM,3500,2024,81663.0,24V DDI OHV Turbo Diesel,6.0,Diesel,10.0,6-Speed Automatic,Laramie,Pickup Truck,4.0,Silver,Black,Four-wheel Drive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
997,2024 Mercedes-Benz Sprinter 2500 Standard Roof,2024 Mercedes-Benz Sprinter 2500 Cargo 144 WB ...,Mercedes-Benz,Sprinter 2500,2024,59037.0,16V DDI DOHC Turbo Diesel,4.0,Diesel,10.0,9-Speed Automatic,Standard Roof,Cargo Van,3.0,Arctic White,Black,Rear-wheel Drive
998,2024 Dodge Hornet Hornet R/T Plus Eawd,Dealer Comments +++ Price Ends 5/31/2024 +++ A...,Dodge,Hornet,2024,49720.0,"4 gasoline direct injection, DOHC, Multiair va...",4.0,Gasoline,0.0,6-Spd Aisin F21-250 PHEV Auto Trans,Hornet R/T Plus Eawd,SUV,4.0,Acapulco Gold,Black,All-wheel Drive
999,2024 Jeep Wagoneer Base,\n \n The ALL New Friendship CDJR ...,Jeep,Wagoneer,2024,69085.0,24V GDI DOHC Twin Turbo,6.0,Gasoline,20.0,8-Speed Automatic,Base,SUV,4.0,Diamond Black,Black,Four-wheel Drive
1000,2024 Nissan Murano SV Intelligent AWD,"\n \n CVT with Xtronic, AWD.At Tod...",Nissan,Murano,2024,43495.0,"6 DOHC, variable valve control, regular unlead...",6.0,Gasoline,6.0,Automatic,SV Intelligent AWD,SUV,4.0,Pearl White Tricoat,Graphite,All-wheel Drive
1001,2024 Chevrolet Silverado 2500 WT,01u 2024 Chevrolet Silverado 2500HD Work Truck...,Chevrolet,Silverado 2500,2024,48995.0,"8 gasoline direct injection, variable valve co...",8.0,Gasoline,31.0,Automatic,WT,Pickup Truck,4.0,Wheatland Yellow,Jet Black,Rear-wheel Drive

In [18]:
#print(df.isnull())
df['fillNA']=df['mileage'].fillna(df['mileage'].mean())
print(df.isnull())

       name  description   make  model   year  price  engine  cylinders  \
0     False        False  False  False  False  False   False      False
1     False        False  False  False  False  False   False      False
2     False         True  False  False  False  False   False      False
3     False        False  False  False  False  False   False      False
4     False        False  False  False  False  False   False      False
...     ...          ...    ...    ...    ...    ...     ...        ...
997   False        False  False  False  False  False   False      False
998   False        False  False  False  False  False   False      False
999   False        False  False  False  False  False   False      False
1000  False        False  False  False  False  False   False      False
1001  False        False  False  False  False  False   False      False

       fuel  mileage  transmission   trim   body  doors  exterior_color  \
0     False    False         False  False  False  False           False
1     False    False         False  False  False  False           False
2     False    False         False  False  False  False           False
3     False    False         False  False  False  False           False
4     False    False         False  False  False  False           False
...     ...      ...           ...    ...    ...    ...             ...
997   False    False         False  False  False  False           False
998   False    False         False  False  False  False           False
999   False    False         False  False  False  False           False
1000  False    False         False  False  False  False           False
1001  False    False         False  False  False  False           False

      interior_color  drivetrain  fillNA
0              False       False   False
1              False       False   False
2              False       False   False
3              False       False   False
4              False       False   False
...              ...         ...     ...
997            False       False   False
998            False       False   False
999            False       False   False
1000           False       False   False
1001           False       False   False

[1002 rows x 18 columns]

In [21]:
#rename coloumn
df=df.rename(columns={'cylinders':'cars cylinder'})
print(df.isna())

       name  description   make  model   year  price  engine  cars cylinder  \
0     False        False  False  False  False  False   False          False
1     False        False  False  False  False  False   False          False
2     False         True  False  False  False  False   False          False
3     False        False  False  False  False  False   False          False
4     False        False  False  False  False  False   False          False
...     ...          ...    ...    ...    ...    ...     ...            ...
997   False        False  False  False  False  False   False          False
998   False        False  False  False  False  False   False          False
999   False        False  False  False  False  False   False          False
1000  False        False  False  False  False  False   False          False
1001  False        False  False  False  False  False   False          False

       fuel  mileage  transmission   trim   body  doors  exterior_color  \
0     False    False         False  False  False  False           False
1     False    False         False  False  False  False           False
2     False    False         False  False  False  False           False
3     False    False         False  False  False  False           False
4     False    False         False  False  False  False           False
...     ...      ...           ...    ...    ...    ...             ...
997   False    False         False  False  False  False           False
998   False    False         False  False  False  False           False
999   False    False         False  False  False  False           False
1000  False    False         False  False  False  False           False
1001  False    False         False  False  False  False           False

      interior_color  drivetrain  fillNA
0              False       False   False
1              False       False   False
2              False       False   False
3              False       False   False
4              False       False   False
...              ...         ...     ...
997            False       False   False
998            False       False   False
999            False       False   False
1000           False       False   False
1001           False       False   False

[1002 rows x 18 columns]

In [26]:
#chnaging datatype
df['new col']=df['cars cylinder'].fillna(0).astype(int)
#df.isna()
df.head(5)

,name,description,make,model,year,price,engine,cars cylinder,fuel,mileage,transmission,trim,body,doors,exterior_color,interior_color,drivetrain,fillNA,new col
0,2024 Jeep Wagoneer Series II,"\n \n Heated Leather Seats, Nav Sy...",Jeep,Wagoneer,2024,74600.0,24V GDI DOHC Twin Turbo,6.0,Gasoline,10.0,8-Speed Automatic,Series II,SUV,4.0,White,Global Black,Four-wheel Drive,10.0,6
1,2024 Jeep Grand Cherokee Laredo,Al West is committed to offering every custome...,Jeep,Grand Cherokee,2024,50170.0,OHV,6.0,Gasoline,1.0,8-Speed Automatic,Laredo,SUV,4.0,Metallic,Global Black,Four-wheel Drive,1.0,6
2,2024 GMC Yukon XL Denali,NaN,GMC,Yukon XL,2024,96410.0,"6.2L V-8 gasoline direct injection, variable v...",8.0,Gasoline,0.0,Automatic,Denali,SUV,4.0,Summit White,Teak/Light Shale,Four-wheel Drive,0.0,8
3,2023 Dodge Durango Pursuit,White Knuckle Clearcoat 2023 Dodge Durango Pur...,Dodge,Durango,2023,46835.0,16V MPFI OHV,8.0,Gasoline,32.0,8-Speed Automatic,Pursuit,SUV,4.0,White Knuckle Clearcoat,Black,All-wheel Drive,32.0,8
4,2024 RAM 3500 Laramie,\n \n 2024 Ram 3500 Laramie Billet...,RAM,3500,2024,81663.0,24V DDI OHV Turbo Diesel,6.0,Diesel,10.0,6-Speed Automatic,Laramie,Pickup Truck,4.0,Silver,Black,Four-wheel Drive,10.0,6

In [ ]:
#applying fn's
df['mileage']=df['mileage'].apply(lambda x:x*2)
df.head(2)

,name,description,make,model,year,price,engine,cars cylinder,fuel,mileage,transmission,trim,body,doors,exterior_color,interior_color,drivetrain,fillNA,new col
0,2024 Jeep Wagoneer Series II,"\n \n Heated Leather Seats, Nav Sy...",Jeep,Wagoneer,2024,74600.0,24V GDI DOHC Twin Turbo,6.0,Gasoline,20.0,8-Speed Automatic,Series II,SUV,4.0,White,Global Black,Four-wheel Drive,10.0,6
1,2024 Jeep Grand Cherokee Laredo,Al West is committed to offering every custome...,Jeep,Grand Cherokee,2024,50170.0,OHV,6.0,Gasoline,2.0,8-Speed Automatic,Laredo,SUV,4.0,Metallic,Global Black,Four-wheel Drive,1.0,6

In [28]:
#group
groupped_mean=df.groupby('mileage')['new col'].mean()
print(groupped_mean)

mileage
0.0        4.663636
2.0        4.068966
4.0        5.620690
6.0        4.228571
8.0        3.900000
             ...
8880.0     4.000000
9002.0     6.000000
9446.0     4.000000
11162.0    6.000000
19422.0    6.000000
Name: new col, Length: 95, dtype: float64

In [30]:
group_sum=df.groupby(['new col','mileage'])['mileage'].sum()
print(group_sum)

new col  mileage
0        0.0          0.0
         2.0         12.0
         6.0         18.0
         8.0         40.0
         10.0       200.0
                    ...
8        196.0      196.0
         210.0      210.0
         296.0      296.0
         394.0      394.0
         894.0      894.0
Name: mileage, Length: 183, dtype: float64

In [31]:
#aggregate multiple functions
group_agg=df.groupby(['new col','mileage'])['mileage'].agg(['mean','sum','count'])
print(group_agg)

                  mean    sum  count
new col mileage
0       0.0        0.0    0.0      8
        2.0        2.0   12.0      6
        6.0        6.0   18.0      3
        8.0        8.0   40.0      5
        10.0      10.0  200.0     20
...                ...    ...    ...
8       196.0    196.0  196.0      1
        210.0    210.0  210.0      1
        296.0    296.0  296.0      1
        394.0    394.0  394.0      1
        894.0    894.0  894.0      1

[183 rows x 3 columns]

In [59]:
#merging and joining dataframes
df1=pd.DataFrame({'key':['A','B','C'],'value':[65,66,67]})
df2=pd.DataFrame({'key':['A','B','C'],'value':[651,66,67]})

df3=pd.DataFrame({'key':['D','E','F'],'value':[68,69,70]})
df4=pd.DataFrame({'key':['D','E','F'],'value':[681,692,703]})
print(df1,"\n",df3)

  key  value
0   A     65
1   B     66
2   C     67
   key  value
0   D     68
1   E     69
2   F     70

In [60]:
#merging on key coloumns
#if a coloumn and data is same

m1=pd.concat([df1,df3])
print(m1)

  key  value
0   A     65
1   B     66
2   C     67
0   D     68
1   E     69
2   F     70

In [61]:
m2=pd.concat([df1,df3],axis=1)
print(m2)

  key  value key  value
0   A     65   D     68
1   B     66   E     69
2   C     67   F     70